import {
  Filter,
  Star,
  TrendingUp,
  Zap,
  Award,
  MapPin,
  Clock,
  Users,
  Tag,
  Wrench,
  ShirtIcon,
  Utensils,
  Sprout,
  Gift,
  Plug,
  Cake,
} from "lucide-react";

export const COLOR_PALETTE = {
  lightBg: "#f8fafc",
  darkText: "#1f2937",
  black: "#000000",
  gray100: "#f3f4f6",
  gray200: "#e5e7eb",
  gray300: "#d1d5db",
  gray400: "#9ca3af",
  gray500: "#6b7280",
  gray600: "#4b5563",
  gray700: "#374151",
  gray800: "#1f2937",
  gray900: "#111827",
  blue50: "#eff6ff",
  blue100: "#dbeafe",
  blue500: "#3b82f6",
  blue600: "#2563eb",
  blue700: "#1d4ed8",
  steelBlue: "rgba(70, 130, 180, 0.5)",
};
export const CATEGORIES_DATA = [
  {
    id: 1,
    name: "Plumber",
    slug: "plumber",
    type: "service",
    icon: Wrench,
    description: "Professional plumbing services for your home",
    badge: "Popular",
    views: 1890,
    rating: 4.8,
    color: COLOR_PALETTE.gray700,
    categories: ["Emergency Plumbing", "Pipe Installation", "Drain Cleaning", "Water Heater Repair"],
    providers: [
      {
        id: 101,
        name: "Rajesh Kumar",
        categories: ["Emergency Plumbing", "Pipe Installation"],
        description: "24/7 emergency plumbing services with 15+ years experience",
        distance: 0.5,
        location: "Sayajigunj",
        image: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400&h=300&fit=crop",
        rating: 4.9,
        views: 1245,
        operatingHours: "24/7",
        phone: "+91 9876543210",
        email: "rajesh.plumber@gmail.com",
        experience: "15+ years",
        likes: 89,
        saved: false,
        liked: false,
      },
      {
        id: 102,
        name: "Amit Patel",
        categories: ["Pipe Installation", "Water Heater Repair"],
        description: "Expert pipe installation and water heater specialist",
        distance: 1.2,
        location: "Alkapuri",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
        rating: 4.7,
        views: 890,
        operatingHours: "9:00 AM - 6:00 PM",
        phone: "+91 9876543211",
        email: "amit.pipes@gmail.com",
        experience: "12+ years",
        likes: 67,
        saved: false,
        liked: false,
      },
      {
        id: 103,
        name: "Suresh Shah",
        categories: ["Drain Cleaning", "Emergency Plumbing"],
        description: "Specialized in drain cleaning and blockage removal",
        distance: 0.8,
        location: "Fatehgunj",
        image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=300&fit=crop",
        rating: 4.6,
        views: 756,
        operatingHours: "8:00 AM - 8:00 PM",
        phone: "+91 9876543212",
        email: "suresh.drains@gmail.com",
        experience: "10+ years",
        likes: 54,
        saved: false,
        liked: false,
      },
      {
        id: 104,
        name: "Vikram Singh",
        categories: ["Water Heater Repair", "Pipe Installation"],
        description: "Specialist in water heater installation and pipe repairs",
        distance: 1.0,
        location: "Gotri",
        image: "https://images.unsplash.com/photo-1581578735760-4f7f698ce3b0?w=400&h=300&fit=crop",
        rating: 4.8,
        views: 920,
        operatingHours: "10:00 AM - 7:00 PM",
        phone: "+91 9876543220",
        email: "vikram.plumbing@gmail.com",
        experience: "14+ years",
        likes: 72,
        saved: false,
        liked: false,
      },
    ],
  },
  {
    id: 2,
    name: "Cobbler",
    slug: "cobbler",
    type: "service",
    icon: ShirtIcon,
    description: "Expert shoe repair and leather services",
    badge: null,
    views: 456,
    rating: 4.3,
    color: COLOR_PALETTE.gray800,
    categories: ["Shoe Repair", "Leather Polishing", "Sole Replacement"],
    providers: [
      {
        id: 201,
        name: "Mohan Chauhan",
        categories: ["Shoe Repair", "Sole Replacement"],
        description: "Traditional cobbler with modern techniques",
        distance: 0.3,
        location: "RC Dutt Road",
        image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=300&fit=crop",
        rating: 4.4,
        views: 234,
        operatingHours: "9:00 AM - 7:00 PM",
        phone: "+91 9876543213",
        email: "mohan.cobbler@gmail.com",
        experience: "20+ years",
        likes: 43,
        saved: false,
        liked: false,
      },
      {
        id: 202,
        name: "Vinod Kumar",
        categories: ["Leather Polishing", "Shoe Repair"],
        description: "Premium leather care and shoe polishing expert",
        distance: 1.5,
        location: "Karelibaug",
        image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400&h=300&fit=crop",
        rating: 4.2,
        views: 189,
        operatingHours: "10:00 AM - 6:00 PM",
        phone: "+91 9876543214",
        email: "vinod.leather@gmail.com",
        experience: "8+ years",
        likes: 32,
        saved: false,
        liked: false,
      },
      {
        id: 203,
        name: "Anil Sharma",
        categories: ["Sole Replacement", "Leather Polishing"],
        description: "Expert in sole replacement and leather restoration",
        distance: 0.7,
        location: "Mandvi",
        image: "https://images.unsplash.com/photo-1605733160314-4fc7f8b0565f?w=400&h=300&fit=crop",
        rating: 4.5,
        views: 210,
        operatingHours: "9:30 AM - 6:30 PM",
        phone: "+91 9876543221",
        email: "anil.cobbler@gmail.com",
        experience: "15+ years",
        likes: 39,
        saved: false,
        liked: false,
      },
    ],
  },
  {
    id: 3,
    name: "Restaurant",
    slug: "restaurant",
    type: "product",
    icon: Utensils,
    description: "Delicious food and dining experiences",
    badge: "Popular",
    views: 3456,
    rating: 4.6,
    color: COLOR_PALETTE.gray700,
    categories: ["Vegetarian", "Non-Vegetarian", "Fast Food", "Fine Dining", "Street Food"],
    providers: [
      {
        id: 501,
        name: "Sagar Restaurant",
        categories: ["Vegetarian", "Fine Dining"],
        description: "Pure vegetarian fine dining with authentic Gujarati cuisine",
        distance: 0.2,
        location: "Alkapuri",
        image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop",
        rating: 4.8,
        views: 2340,
        operatingHours: "11:00 AM - 11:00 PM",
        phone: "+91 9876543215",
        email: "sagar.restaurant@gmail.com",
        cuisine: "Gujarati",
        likes: 156,
        saved: false,
        liked: false,
      },
      {
        id: 502,
        name: "Spice Garden",
        categories: ["Non-Vegetarian", "Fast Food"],
        description: "Multi-cuisine restaurant with quick service",
        distance: 1.4,
        location: "Fatehgunj",
        image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=300&fit=crop",
        rating: 4.7,
        views: 1980,
        operatingHours: "12:00 PM - 12:00 AM",
        phone: "+91 9876543216",
        email: "spice.garden@gmail.com",
        cuisine: "Multi-cuisine",
        likes: 134,
        saved: false,
        liked: false,
      },
      {
        id: 503,
        name: "Street Bites",
        categories: ["Street Food", "Fast Food"],
        description: "Authentic Vadodara street food experience",
        distance: 0.5,
        location: "Mandvi",
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop",
        rating: 4.5,
        views: 2100,
        operatingHours: "6:00 PM - 11:00 PM",
        phone: "+91 9876543217",
        email: "street.bites@gmail.com",
        cuisine: "Local Street Food",
        likes: 187,
        saved: false,
        liked: false,
      },
      {
        id: 504,
        name: "Taste of Punjab",
        categories: ["Non-Vegetarian", "Fine Dining"],
        description: "Authentic Punjabi cuisine with a luxurious dining experience",
        distance: 0.9,
        location: "Sayajigunj",
        image: "https://images.unsplash.com/photo-1590846406792-0c40c838722f?w=400&h=300&fit=crop",
        rating: 4.9,
        views: 1750,
        operatingHours: "12:00 PM - 11:00 PM",
        phone: "+91 9876543222",
        email: "punjab.taste@gmail.com",
        cuisine: "Punjabi",
        likes: 145,
        saved: false,
        liked: false,
      },
    ],
  },
  {
    id: 4,
    name: "Mali (Gardener)",
    slug: "mali",
    type: "service",
    icon: Sprout,
    description: "Professional gardening and landscaping",
    badge: "Top Rated",
    views: 876,
    rating: 4.9,
    color: COLOR_PALETTE.gray800,
    categories: ["Garden Maintenance", "Plant Installation", "Lawn Care", "Landscaping"],
    providers: [
      {
        id: 601,
        name: "Raman Mali",
        categories: ["Garden Maintenance", "Plant Installation"],
        description: "Expert gardener with specialization in local plants",
        distance: 1.3,
        location: "Gotri",
        image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop",
        rating: 4.9,
        views: 540,
        operatingHours: "7:00 AM - 6:00 PM",
        phone: "+91 9876543218",
        email: "raman.mali@gmail.com",
        experience: "18+ years",
        likes: 98,
        saved: false,
        liked: false,
      },
      {
        id: 602,
        name: "Kiran Patel",
        categories: ["Landscaping", "Lawn Care"],
        description: "Professional landscape designer and lawn specialist",
        distance: 2.0,
        location: "Vasna",
        image: "https://images.unsplash.com/photo-1558904541-efa843a96239?w=400&h=300&fit=crop",
        rating: 4.8,
        views: 280,
        operatingHours: "8:00 AM - 6:00 PM",
        phone: "+91 9876543219",
        email: "kiran.landscape@gmail.com",
        experience: "12+ years",
        likes: 76,
        saved: false,
        liked: false,
      },
      {
        id: 603,
        name: "Sunil Yadav",
        categories: ["Garden Maintenance", "Lawn Care"],
        description: "Skilled gardener for lawn care and garden upkeep",
        distance: 1.8,
        location: "Karelibaug",
        image: "https://images.unsplash.com/photo-1585320806291-7b3c81e9ddff?w=400&h=300&fit=crop",
        rating: 4.7,
        views: 320,
        operatingHours: "7:30 AM - 5:30 PM",
        phone: "+91 9876543223",
        email: "sunil.gardens@gmail.com",
        experience: "10+ years",
        likes: 85,
        saved: false,
        liked: false,
      },
    ],
  },
  {
    id: 5,
    name: "Electrician",
    slug: "electrician",
    type: "service",
    icon: Plug,
    description: "Expert electrical services for residential and commercial needs",
    badge: "Highly Rated",
    views: 1432,
    rating: 4.7,
    color: COLOR_PALETTE.gray700,
    categories: ["Wiring", "Lighting Installation", "Appliance Repair", "Circuit Breaker Services"],
    providers: [
      {
        id: 701,
        name: "Mahesh Desai",
        categories: ["Wiring", "Lighting Installation"],
        description: "Certified electrician for home wiring and lighting solutions",
        distance: 0.6,
        location: "Alkapuri",
        image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
        rating: 4.8,
        views: 980,
        operatingHours: "8:00 AM - 7:00 PM",
        phone: "+91 9876543224",
        email: "mahesh.electric@gmail.com",
        experience: "16+ years",
        likes: 92,
        saved: false,
        liked: false,
      },
      {
        id: 702,
        name: "Prakash Joshi",
        categories: ["Appliance Repair", "Circuit Breaker Services"],
        description: "Specialist in appliance repair and circuit maintenance",
        distance: 1.1,
        location: "Fatehgunj",
        image: "https://images.unsplash.com/photo-1570544826585-8dd0cf1e48b9?w=400&h=300&fit=crop",
        rating: 4.6,
        views: 650,
        operatingHours: "9:00 AM - 6:00 PM",
        phone: "+91 9876543225",
        email: "prakash.electrical@gmail.com",
        experience: "11+ years",
        likes: 78,
        saved: false,
        liked: false,
      },
    ],
  },
  {
    id: 6,
    name: "Bakery",
    slug: "bakery",
    type: "product",
    icon: Cake,
    description: "Freshly baked goods and custom cakes",
    badge: "Popular",
    views: 2678,
    rating: 4.5,
    color: COLOR_PALETTE.gray800,
    categories: ["Cakes", "Pastries", "Breads", "Cookies"],
    providers: [
      {
        id: 801,
        name: "Sweet Delights Bakery",
        categories: ["Cakes", "Pastries"],
        description: "Custom cakes and delicious pastries for all occasions",
        distance: 0.4,
        location: "Sayajigunj",
        image: "https://images.unsplash.com/photo-1563729788314-1f90f36a3b3e?w=400&h=300&fit=crop",
        rating: 4.7,
        views: 1650,
        operatingHours: "8:00 AM - 9:00 PM",
        phone: "+91 9876543226",
        email: "sweet.delights@gmail.com",
        cuisine: "Bakery",
        likes: 120,
        saved: false,
        liked: false,
      },
      {
        id: 802,
        name: "Golden Crust",
        categories: ["Breads", "Cookies"],
        description: "Artisanal breads and freshly baked cookies",
        distance: 1.0,
        location: "Gotri",
        image: "https://images.unsplash.com/photo-1548365328-8c6d5b9b6c2c?w=400&h=300&fit=crop",
        rating: 4.4,
        views: 890,
        operatingHours: "7:00 AM - 8:00 PM",
        phone: "+91 9876543227",
        email: "golden.crust@gmail.com",
        cuisine: "Bakery",
        likes: 95,
        saved: false,
        liked: false,
      },
    ],
  },
];

// export const CATEGORIES_DATA = [
//   {
//     id: 1,
//     name: "Plumber",
//     slug: "plumber",
//     type: "service",
//     icon: Wrench,
//     description: "Professional plumbing services for your home",
//     badge: "Popular",
//     views: 1890,
//     rating: 4.8,
//     color: COLOR_PALETTE.gray700,
//     categories: ["Emergency Plumbing", "Pipe Installation", "Drain Cleaning", "Water Heater Repair"],
//     providers: [
//       {
//         id: 101,
//         name: "Rajesh Kumar",
//         categories: ["Emergency Plumbing", "Pipe Installation"],
//         description: "24/7 emergency plumbing services with 15+ years experience",
//         distance: 0.5,
//         location: "Sayajigunj",
//         image: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400&h=300&fit=crop",
//         rating: 4.9,
//         views: 1245,
//         operatingHours: "24/7",
//         phone: "+91 9876543210",
//         email: "rajesh.plumber@gmail.com",
//         experience: "15+ years",
//         likes: 89,
//         saved: false,
//         liked: false,
//       },
//       {
//         id: 102,
//         name: "Amit Patel",
//         categories: ["Pipe Installation", "Water Heater Repair"],
//         description: "Expert pipe installation and water heater specialist",
//         distance: 1.2,
//         location: "Alkapuri",
//         image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
//         rating: 4.7,
//         views: 890,
//         operatingHours: "9:00 AM - 6:00 PM",
//         phone: "+91 9876543211",
//         email: "amit.pipes@gmail.com",
//         experience: "12+ years",
//         likes: 67,
//         saved: false,
//         liked: false,
//       },
//       {
//         id: 103,
//         name: "Suresh Shah",
//         categories: ["Drain Cleaning", "Emergency Plumbing"],
//         description: "Specialized in drain cleaning and blockage removal",
//         distance: 0.8,
//         location: "Fatehgunj",
//         image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=300&fit=crop",
//         rating: 4.6,
//         views: 756,
//         operatingHours: "8:00 AM - 8:00 PM",
//         phone: "+91 9876543212",
//         email: "suresh.drains@gmail.com",
//         experience: "10+ years",
//         likes: 54,
//         saved: false,
//         liked: false,
//       },
//     ],
//   },
//   {
//     id: 2,
//     name: "Cobbler",
//     slug: "cobbler",
//     type: "service",
//     icon: ShirtIcon,
//     description: "Expert shoe repair and leather services",
//     badge: null,
//     views: 456,
//     rating: 4.3,
//     color: COLOR_PALETTE.gray800,
//     categories: ["Shoe Repair", "Leather Polishing", "Sole Replacement"],
//     providers: [
//       {
//         id: 201,
//         name: "Mohan Chauhan",
//         categories: ["Shoe Repair", "Sole Replacement"],
//         description: "Traditional cobbler with modern techniques",
//         distance: 0.3,
//         location: "RC Dutt Road",
//         image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=300&fit=crop",
//         rating: 4.4,
//         views: 234,
//         operatingHours: "9:00 AM - 7:00 PM",
//         phone: "+91 9876543213",
//         email: "mohan.cobbler@gmail.com",
//         experience: "20+ years",
//         likes: 43,
//         saved: false,
//         liked: false,
//       },
//       {
//         id: 202,
//         name: "Vinod Kumar",
//         categories: ["Leather Polishing", "Shoe Repair"],
//         description: "Premium leather care and shoe polishing expert",
//         distance: 1.5,
//         location: "Karelibaug",
//         image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400&h=300&fit=crop",
//         rating: 4.2,
//         views: 189,
//         operatingHours: "10:00 AM - 6:00 PM",
//         phone: "+91 9876543214",
//         email: "vinod.leather@gmail.com",
//         experience: "8+ years",
//         likes: 32,
//         saved: false,
//         liked: false,
//       },
//     ],
//   },
//   {
//     id: 3,
//     name: "Restaurant",
//     slug: "restaurant",
//     type: "product",
//     icon: Utensils,
//     description: "Delicious food and dining experiences",
//     badge: "Popular",
//     views: 3456,
//     rating: 4.6,
//     color: COLOR_PALETTE.gray700,
//     categories: ["Vegetarian", "Non-Vegetarian", "Fast Food", "Fine Dining", "Street Food"],
//     providers: [
//       {
//         id: 501,
//         name: "Sagar Restaurant",
//         categories: ["Vegetarian", "Fine Dining"],
//         description: "Pure vegetarian fine dining with authentic Gujarati cuisine",
//         distance: 0.2,
//         location: "Alkapuri",
//         image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400&h=300&fit=crop",
//         rating: 4.8,
//         views: 2340,
//         operatingHours: "11:00 AM - 11:00 PM",
//         phone: "+91 9876543215",
//         email: "sagar.restaurant@gmail.com",
//         cuisine: "Gujarati",
//         likes: 156,
//         saved: false,
//         liked: false,
//       },
//       {
//         id: 502,
//         name: "Spice Garden",
//         categories: ["Non-Vegetarian", "Fast Food"],
//         description: "Multi-cuisine restaurant with quick service",
//         distance: 1.4,
//         location: "Fatehgunj",
//         image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=300&fit=crop",
//         rating: 4.7,
//         views: 1980,
//         operatingHours: "12:00 PM - 12:00 AM",
//         phone: "+91 9876543216",
//         email: "spice.garden@gmail.com",
//         cuisine: "Multi-cuisine",
//         likes: 134,
//         saved: false,
//         liked: false,
//       },
//       {
//         id: 503,
//         name: "Street Bites",
//         categories: ["Street Food", "Fast Food"],
//         description: "Authentic Vadodara street food experience",
//         distance: 0.5,
//         location: "Mandvi",
//         image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop",
//         rating: 4.5,
//         views: 2100,
//         operatingHours: "6:00 PM - 11:00 PM",
//         phone: "+91 9876543217",
//         email: "street.bites@gmail.com",
//         cuisine: "Local Street Food",
//         likes: 187,
//         saved: false,
//         liked: false,
//       },
//     ],
//   },
//   {
//     id: 4,
//     name: "Mali (Gardener)",
//     slug: "mali",
//     type: "service",
//     icon: Sprout,
//     description: "Professional gardening and landscaping",
//     badge: "Top Rated",
//     views: 876,
//     rating: 4.9,
//     color: COLOR_PALETTE.gray800,
//     categories: ["Garden Maintenance", "Plant Installation", "Lawn Care", "Landscaping"],
//     providers: [
//       {
//         id: 601,
//         name: "Raman Mali",
//         categories: ["Garden Maintenance", "Plant Installation"],
//         description: "Expert gardener with specialization in local plants",
//         distance: 1.3,
//         location: "Gotri",
//         image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop",
//         rating: 4.9,
//         views: 540,
//         operatingHours: "7:00 AM - 6:00 PM",
//         phone: "+91 9876543218",
//         email: "raman.mali@gmail.com",
//         experience: "18+ years",
//         likes: 98,
//         saved: false,
//         liked: false,
//       },
//       {
//         id: 602,
//         name: "Kiran Patel",
//         categories: ["Landscaping", "Lawn Care"],
//         description: "Professional landscape designer and lawn specialist",
//         distance: 2.0,
//         location: "Vasna",
//         image: "https://images.unsplash.com/photo-1558904541-efa843a96239?w=400&h=300&fit=crop",
//         rating: 4.8,
//         views: 280,
//         operatingHours: "8:00 AM - 6:00 PM",
//         phone: "+91 9876543219",
//         email: "kiran.landscape@gmail.com",
//         experience: "12+ years",
//         likes: 76,
//         saved: false,
//         liked: false,
//       },
//     ],
//   },
// ];

export const SORT_OPTIONS = [
  { key: "distance", label: "Distance", icon: MapPin },
  { key: "rating", label: "Rating", icon: Star },
  { key: "views", label: "Views", icon: Users },
  { key: "time", label: "Time", icon: Clock },
  { key: "name", label: "Name", icon: Tag },
];

export const FILTER_OPTIONS = [
  { value: "all", label: "All Badges", icon: Filter },
  { value: "popular", label: "Popular", icon: Users },
  { value: "trending", label: "Trending", icon: TrendingUp },
  { value: "new", label: "New", icon: Zap },
  { value: "top-rated", label: "Top Rated", icon: Award },
];

export const CATEGORY_TYPE_OPTIONS = [
  { key: "all", label: "All Categories", icon: Users },
  { key: "service", label: "Services", icon: Wrench },
  { key: "product", label: "Products", icon: Gift },
];