import {
  Filter,
  Star,
  TrendingUp,
  Zap,
  Award,
  MapPin,
  Clock,
  Users,
  Tag,
  Wrench,
  ShirtIcon,
  Utensils,
  Sprout,
  Gift,
  Plug,
  Cake,
  Flower,
  Scissors,
  Hammer,
  Coffee,
  Dumbbell,
  Truck,
  GraduationCap,
  Stethoscope,
  ShoppingBag,
  Film,
  MoreHorizontal,
  User,
} from "lucide-react";

export const COLOR_PALETTE = {
  lightBg: "#f8fafc",
  darkText: "#1f2937",
  black: "#000000",
  gray100: "#f3f4f6",
  gray200: "#e5e7eb",
  gray300: "#d1d5db",
  gray400: "#9ca3af",
  gray500: "#6b7280",
  gray600: "#4b5563",
  gray700: "#374151",
  gray800: "#1f2937",
  gray900: "#111827",
  blue50: "#eff6ff",
  blue100: "#dbeafe",
  blue500: "#3b82f6",
  blue600: "#2563eb",
  blue700: "#1d4ed8",
  steelBlue: "rgba(70, 130, 180, 0.5)",
};

export const CATEGORIES_DATA = [
  {
    id: 1,
    name: "Restaurant",
    slug: "restaurant",
    description: "Discover top-rated restaurants offering delicious cuisines and cozy ambiance.",
    icon: Utensils,
    type: "service",
    badge: "Popular",
    rating: 4.8,
    views: 2400,
    providers: [{ name: "Food Lounge" }, { name: "Spice Villa" }],
  },
  {
    id: 2,
    name: "Cafe",
    slug: "cafe",
    description: "Find cozy cafes perfect for coffee, conversations, and creativity.",
    icon: Coffee,
    type: "service",
    badge: "Trending",
    rating: 4.7,
    views: 1800,
    providers: [{ name: "Brew Haven" }, { name: "Mocha Magic" }],
  },
  {
    id: 3,
    name: "Gym",
    slug: "gym",
    description: "Stay fit and active with top fitness centers and personal training programs.",
    icon: Dumbbell,
    type: "service",
    badge: "Top Rated",
    rating: 4.9,
    views: 3000,
    providers: [{ name: "PowerZone" }, { name: "FlexHub" }],
  },
  {
    id: 4,
    name: "Salon",
    slug: "salon",
    description: "Premium beauty and grooming salons for men and women near you.",
    icon: Scissors,
    type: "service",
    badge: "New",
    rating: 4.6,
    views: 1600,
    providers: [{ name: "StyleCraft" }, { name: "Glow Studio" }],
  },
  {
    id: 5,
    name: "Transport",
    slug: "transport",
    description: "Reliable transportation and logistics services for your daily needs.",
    icon: Truck,
    type: "service",
    badge: "Popular",
    rating: 4.4,
    views: 1300,
    providers: [{ name: "QuickMove" }, { name: "RidePro" }],
  },
  {
    id: 6,
    name: "Education",
    slug: "education",
    description: "Trusted institutions and learning centers to help you grow your skills.",
    icon: GraduationCap,
    type: "service",
    badge: "Trending",
    rating: 4.8,
    views: 2700,
    providers: [{ name: "Bright Academy" }, { name: "SkillBridge" }],
  },
  {
    id: 7,
    name: "Medical",
    slug: "medical",
    description: "Hospitals, clinics, and pharmacies offering quality healthcare services.",
    icon: Stethoscope,
    type: "service",
    badge: "Top Rated",
    rating: 4.9,
    views: 3500,
    providers: [{ name: "LifeCare" }, { name: "MediTrust" }],
  },
  {
    id: 8,
    name: "Shopping",
    slug: "shopping",
    description: "Explore malls, stores, and boutiques for your favorite brands and trends.",
    icon: ShoppingBag,
    type: "service",
    badge: "Popular",
    rating: 4.7,
    views: 2200,
    providers: [{ name: "StyleKart" }, { name: "ShopNest" }],
  },
  {
    id: 9,
    name: "Entertainment",
    slug: "entertainment",
    description: "Discover movies, events, and fun activities happening around you.",
    icon: Film,
    type: "service",
    badge: "Trending",
    rating: 4.5,
    views: 2000,
    providers: [{ name: "FunZone" }, { name: "EventHub" }],
  },
  {
    id: 10,
    name: "Services",
    slug: "services",
    description: "Professional repair, cleaning, and maintenance services near you.",
    icon: Wrench,
    type: "service",
    badge: "Top Rated",
    rating: 4.8,
    views: 2100,
    providers: [{ name: "FixMate" }, { name: "CleanPro" }],
  },
  {
    id: 11,
    name: "Other",
    slug: "other",
    description: "Miscellaneous businesses offering unique and niche services.",
    icon: MoreHorizontal,
    type: "service",
    badge: "New",
    rating: 4.3,
    views: 900,
    providers: [{ name: "UniServe" }],
  },
];
export const SORT_OPTIONS = [
  { key: "distance", label: "Distance", icon: MapPin },
  { key: "rating", label: "Rating", icon: Star },
  { key: "views", label: "Views", icon: Users },
  { key: "time", label: "Time", icon: Clock },
  { key: "name", label: "Name", icon: Tag },
];

export const FILTER_OPTIONS = [
  { value: "all", label: "All Badges", icon: Filter },
  { value: "popular", label: "Popular", icon: Users },
  { value: "trending", label: "Trending", icon: TrendingUp },
  { value: "new", label: "New", icon: Zap },
  { value: "top-rated", label: "Top Rated", icon: Award },
];

export const CATEGORY_TYPE_OPTIONS = [
  { key: "all", label: "All Categories", icon: Users },
  { key: "service", label: "Services", icon: Wrench },
  { key: "product", label: "Products", icon: Gift },
];